language: dart

dart:
  # Install the latest stable release
  # - dev
  - stable
  # - 2.0.0

#with_content_shell: true
dart_task:
- test: --platform vm
- test: --platform chrome
- test: --platform firefox
