name: pathfinding_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/xaguzman/pathfinding-dart
author: Xavier Guzman <xaguzman@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  tweenengine: ^0.12.1